# Generated by Django 4.2.9 on 2024-02-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("แบบรองกระสอบ", "แบบรองกระสอบ"),
                            ("แบบถังอุ้ม", "แบบถังอุ้ม"),
                        ],
                        max_length=100,
                    ),
                ),
                ("price", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
