# Generated by Django 5.0.2 on 2024-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Driver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vehicle_images/",
                verbose_name="รูปภาพรถ",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(max_length=100, verbose_name="รุ่น"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="ราคา"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="province",
            field=models.CharField(max_length=200, verbose_name="จังหวัดที่ลงพื้นที่"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("แบบรองกระสอบ", "แบบรองกระสอบ"),
                    ("แบบถังอุ้ม", "แบบถังอุ้ม"),
                ],
                max_length=100,
                verbose_name="ประเภทรถ",
            ),
        ),
    ]
