# Generated by Django 5.0.2 on 2024-04-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Driver", "0002_alter_vehicle_image_alter_vehicle_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detailvehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power",
                    models.CharField(max_length=100, verbose_name="กำลังเครื่อง"),
                ),
                ("details", models.TextField(verbose_name="รายละเอียด")),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles_detailvehicle",
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
