# Generated by Django 5.0.2 on 2024-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Driver", "0004_alter_vehicle_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_working",
            field=models.BooleanField(default=False, verbose_name="สถานะการทำงาน"),
        ),
    ]
