# Generated by Django 5.0.2 on 2024-05-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Driver", "0006_remove_vehicle_is_working"),
        ("Farmer", "0002_booking_vehicle_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่ส่ง"),
                ),
                (
                    "delivery_time",
                    models.TimeField(blank=True, null=True, verbose_name="เวลาส่ง"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.userdriver",
                    ),
                ),
                (
                    "farmer_booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_booking",
                        to="Farmer.booking",
                    ),
                ),
            ],
        ),
    ]
