# Generated by Django 5.0.2 on 2024-05-13 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Driver", "0007_driverbooking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverBooking",
        ),
    ]
