# Generated by Django 5.0.2 on 2024-06-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_remove_userdriver_driver_license_and_more"),
        ("Driver", "0011_calendarevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="license_documents/")),
                ("is_approved", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_documents",
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
