# Generated by Django 5.0.2 on 2024-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Driver", "0012_licensedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensedocument",
            name="can_resubmit",
            field=models.BooleanField(default=True),
        ),
    ]
