# Generated by Django 5.0.2 on 2024-06-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("quantity", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
                ("details", models.TextField()),
                (
                    "request_responded_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("request_status", models.CharField(default="Pending", max_length=30)),
                ("appointment_start_date", models.DateTimeField(blank=True, null=True)),
                ("appointment_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="accounts.userfarmer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drivers.vehicle",
                    ),
                ),
            ],
        ),
    ]
