# Generated by Django 5.0.2 on 2024-06-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_userdriver_groups_and_more"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="farmer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "farmer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="accounts.customuser",
            ),
        ),
    ]
