# Generated by Django 5.0.2 on 2024-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
