# Generated by Django 5.0.2 on 2024-07-06 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_alter_booking_request_responded_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="request_responded_by",
        ),
    ]
