# Generated by Django 5.0.2 on 2024-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_booking_harvest_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="harvest_area",
        ),
        migrations.AddField(
            model_name="booking",
            name="district",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="province",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="subdistrict",
            field=models.CharField(default="", max_length=100),
        ),
    ]
