# Generated by Django 5.0.2 on 2024-07-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_remove_booking_harvest_area_booking_district_and_more"),
        ("drivers", "0021_alter_harvestarea_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="district",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="province",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="subdistrict",
        ),
        migrations.AddField(
            model_name="booking",
            name="harvest_area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drivers.harvestarea",
            ),
        ),
    ]
