# Generated by Django 5.0.2 on 2024-07-20 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_booking_district_booking_province_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="district",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="province",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="subdistrict",
        ),
    ]
