# Generated by Django 5.0.2 on 2024-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0010_remove_booking_district_remove_booking_province_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="harvest_area",
        ),
        migrations.AddField(
            model_name="booking",
            name="district",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="province",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="subdistrict",
            field=models.CharField(default="", max_length=100),
        ),
    ]
