# Generated by Django 5.0.2 on 2024-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0011_remove_booking_harvest_area_booking_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="request_status",
            field=models.CharField(default="รอดำเนินการ", max_length=30),
        ),
    ]
