# Generated by Django 5.0.2 on 2024-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
