# Generated by Django 5.0.2 on 2024-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
