# Generated by Django 5.0.2 on 2024-06-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.FileField(upload_to="license_documents/id_card/")),
                (
                    "driving_license",
                    models.FileField(upload_to="license_documents/driving_license/"),
                ),
                (
                    "vehicle_registration",
                    models.FileField(
                        upload_to="license_documents/vehicle_registration/"
                    ),
                ),
                (
                    "driver_photo",
                    models.ImageField(upload_to="license_documents/driver_photo/"),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(upload_to="license_documents/vehicle_photo/"),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("can_resubmit", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_documents",
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
