# Generated by Django 5.0.2 on 2024-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licensedocument",
            name="driver_photo",
        ),
        migrations.RemoveField(
            model_name="licensedocument",
            name="rejection_reason",
        ),
        migrations.RemoveField(
            model_name="licensedocument",
            name="vehicle_photo",
        ),
        migrations.AddField(
            model_name="licensedocument",
            name="photo",
            field=models.ImageField(default="", upload_to="license_documents/photo/"),
        ),
        migrations.AddField(
            model_name="licensedocument",
            name="reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
