# Generated by Django 5.0.2 on 2024-06-08 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_admin", "0002_remove_licensedocument_driver_photo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LicenseDocument",
        ),
    ]
