# Generated by Django 5.0.2 on 2024-06-08 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_driver_farmer"),
        ("auth_admin", "0003_delete_licensedocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("id_card", models.ImageField(upload_to="documents/id_card/")),
                (
                    "car_registration",
                    models.ImageField(upload_to="documents/car_registration/"),
                ),
                (
                    "driver_with_car",
                    models.ImageField(upload_to="documents/driver_with_car/"),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("request_status", models.CharField(default="Pending", max_length=30)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
    ]
