# Generated by Django 5.0.2 on 2024-06-11 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_admin", "0005_driverdocument_notification_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverdocument",
            name="notification_status",
        ),
    ]
