# Generated by Django 5.0.2 on 2024-06-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detailvehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power",
                    models.CharField(max_length=100, verbose_name="กำลังเครื่อง"),
                ),
                ("details", models.TextField(verbose_name="รายละเอียด")),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles_detailvehicle",
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="license_documents/")),
                ("is_approved", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("can_resubmit", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_documents",
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="รุ่น")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("แบบรองกระสอบ", "แบบรองกระสอบ"),
                            ("แบบถังอุ้ม", "แบบถังอุ้ม"),
                        ],
                        max_length=100,
                        verbose_name="ประเภทรถ",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="ราคา"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("กระบี่", "กระบี่"),
                            ("กรุงเทพมหานคร", "กรุงเทพมหานคร"),
                            ("กาญจนบุรี", "กาญจนบุรี"),
                            ("กาฬสินธุ์", "กาฬสินธุ์"),
                            ("กำแพงเพชร", "กำแพงเพชร"),
                            ("ขอนแก่น", "ขอนแก่น"),
                            ("จันทบุรี", "จันทบุรี"),
                            ("ฉะเชิงเทรา", "ฉะเชิงเทรา"),
                            ("ชลบุรี", "ชลบุรี"),
                            ("ชัยนาท", "ชัยนาท"),
                            ("ชัยภูมิ", "ชัยภูมิ"),
                            ("ชุมพร", "ชุมพร"),
                            ("เชียงราย", "เชียงราย"),
                            ("เชียงใหม่", "เชียงใหม่"),
                            ("ตรัง", "ตรัง"),
                            ("ตราด", "ตราด"),
                            ("ตาก", "ตาก"),
                            ("นครนายก", "นครนายก"),
                            ("นครปฐม", "นครปฐม"),
                            ("นครพนม", "นครพนม"),
                            ("นครราชสีมา", "นครราชสีมา"),
                            ("นครศรีธรรมราช", "นครศรีธรรมราช"),
                            ("นครสวรรค์", "นครสวรรค์"),
                            ("นนทบุรี", "นนทบุรี"),
                            ("นราธิวาส", "นราธิวาส"),
                            ("น่าน", "น่าน"),
                            ("บึงกาฬ", "บึงกาฬ"),
                            ("บุรีรัมย์", "บุรีรัมย์"),
                            ("ปทุมธานี", "ปทุมธานี"),
                            ("ประจวบคีรีขันธ์", "ประจวบคีรีขันธ์"),
                            ("ปราจีนบุรี", "ปราจีนบุรี"),
                            ("ปัตตานี", "ปัตตานี"),
                            ("พระนครศรีอยุธยา", "พระนครศรีอยุธยา"),
                            ("พะเยา", "พะเยา"),
                            ("พังงา", "พังงา"),
                            ("พัทลุง", "พัทลุง"),
                            ("พิจิตร", "พิจิตร"),
                            ("พิษณุโลก", "พิษณุโลก"),
                            ("เพชรบุรี", "เพชรบุรี"),
                            ("เพชรบูรณ์", "เพชรบูรณ์"),
                            ("แพร่", "แพร่"),
                            ("พะเยา", "พะเยา"),
                            ("ภูเก็ต", "ภูเก็ต"),
                            ("มหาสารคาม", "มหาสารคาม"),
                            ("มุกดาหาร", "มุกดาหาร"),
                            ("แม่ฮ่องสอน", "แม่ฮ่องสอน"),
                            ("ยโสธร", "ยโสธร"),
                            ("ยะลา", "ยะลา"),
                            ("ร้อยเอ็ด", "ร้อยเอ็ด"),
                            ("ระนอง", "ระนอง"),
                            ("ระยอง", "ระยอง"),
                            ("ราชบุรี", "ราชบุรี"),
                            ("ลพบุรี", "ลพบุรี"),
                            ("ลำปาง", "ลำปาง"),
                            ("ลำพูน", "ลำพูน"),
                            ("เลย", "เลย"),
                            ("ศรีสะเกษ", "ศรีสะเกษ"),
                            ("สกลนคร", "สกลนคร"),
                            ("สงขลา", "สงขลา"),
                            ("สตูล", "สตูล"),
                            ("สมุทรปราการ", "สมุทรปราการ"),
                            ("สมุทรสงคราม", "สมุทรสงคราม"),
                            ("สมุทรสาคร", "สมุทรสาคร"),
                            ("สระแก้ว", "สระแก้ว"),
                            ("สระบุรี", "สระบุรี"),
                            ("สิงห์บุรี", "สิงห์บุรี"),
                            ("สุโขทัย", "สุโขทัย"),
                            ("สุพรรณบุรี", "สุพรรณบุรี"),
                            ("สุราษฎร์ธานี", "สุราษฎร์ธานี"),
                            ("สุรินทร์", "สุรินทร์"),
                            ("หนองคาย", "หนองคาย"),
                            ("หนองบัวลำภู", "หนองบัวลำภู"),
                            ("อ่างทอง", "อ่างทอง"),
                            ("อำนาจเจริญ", "อำนาจเจริญ"),
                            ("อุดรธานี", "อุดรธานี"),
                            ("อุตรดิตถ์", "อุตรดิตถ์"),
                            ("อุทัยธานี", "อุทัยธานี"),
                            ("อุบลราชธานี", "อุบลราชธานี"),
                            ("อำนาจเจริญ", "อำนาจเจริญ"),
                        ],
                        max_length=200,
                        verbose_name="จังหวัดที่ลงพื้นที่",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicle_images/",
                        verbose_name="รูปภาพรถ",
                    ),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
