# Generated by Django 5.0.2 on 2024-06-07 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LicenseDocument",
        ),
    ]
