# Generated by Django 5.0.2 on 2024-06-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_userdriver_groups_and_more"),
        ("drivers", "0002_delete_licensedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailvehicle",
            name="driver",
        ),
        migrations.AddField(
            model_name="detailvehicle",
            name="vehicle",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="drivers.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="accounts.customuser",
            ),
        ),
    ]
