# Generated by Django 5.0.2 on 2024-06-11 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0005_alter_detailvehicle_vehicle_calendarevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailvehicle",
            name="vehicle",
        ),
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
        migrations.DeleteModel(
            name="Detailvehicle",
        ),
    ]
