# Generated by Django 5.0.2 on 2024-06-13 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0007_vehicleimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleImage",
        ),
    ]
