# Generated by Django 5.0.2 on 2024-07-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0012_vehicle_max_acres_per_day_vehicle_min_acres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start",
            field=models.DateTimeField(),
        ),
    ]
