# Generated by Django 5.0.2 on 2024-07-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customuser_is_staff"),
        ("drivers", "0014_calendarevent_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="farmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="accounts.customuser",
            ),
        ),
    ]
