# Generated by Django 5.0.2 on 2024-07-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customuser_is_staff"),
        ("drivers", "0017_harvestarea_delete_servicearea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvestarea",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.customuser"
            ),
        ),
    ]
