# Generated by Django 5.0.2 on 2024-07-17 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0018_alter_harvestarea_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harvestarea",
            name="end_date",
        ),
    ]
