# Generated by Django 5.0.2 on 2024-07-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0020_harvestarea_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvestarea",
            name="end_date",
            field=models.DateField(),
        ),
    ]
