# Generated by Django 5.0.2 on 2024-07-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0022_vehicleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="กำลังเครื่อง",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="vehicle_images/", verbose_name="รูปภาพรถ"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายละเอียดรถ"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="drivers.vehicle",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VehicleImage",
        ),
    ]
