# Generated by Django 5.0.2 on 2024-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0026_alter_vehicledetail_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledetail",
            name="image10",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image5",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image6",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image7",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image8",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="image9",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="details",
            field=models.TextField(verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_details/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="power",
            field=models.CharField(max_length=100, verbose_name="กำลังเครื่อง"),
        ),
    ]
