# Generated by Django 5.0.2 on 2024-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0027_vehicledetail_image10_vehicledetail_image4_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image10",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image7",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image8",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="image9",
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vehicle_detail_images/",
                verbose_name="รูปภาพ 1",
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vehicle_detail_images/",
                verbose_name="รูปภาพ 2",
            ),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vehicle_detail_images/",
                verbose_name="รูปภาพ 3",
            ),
        ),
    ]
