# Generated by Django 5.0.2 on 2024-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0029_vehicledetail_model_alter_vehicledetail_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicledetail",
            name="model",
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="details",
            field=models.TextField(verbose_name="รายละเอียดรถ"),
        ),
    ]
