# Generated by Django 5.0.2 on 2024-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0030_remove_vehicledetail_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetail",
            name="details",
            field=models.TextField(default="", verbose_name="รายละเอียดรถ"),
        ),
    ]
