# Generated by Django 5.0.2 on 2024-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0031_alter_vehicledetail_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="max_acres_per_day",
            field=models.IntegerField(
                default="", verbose_name="จำนวนไร่สูงสุดที่เกี่ยวได้ต่อวัน (ไร่)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="min_acres",
            field=models.IntegerField(
                default="", verbose_name="ขั้นต่ำที่รับเกี่ยว (ไร่)"
            ),
        ),
    ]
