# Generated by Django 5.0.2 on 2024-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0033_calendarevent_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=True, verbose_name='สถานะการให้บริการ'),
        ),
    ]
