# Generated by Django 5.0.2 on 2024-09-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0035_alter_vehicledetail_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='drivers.vehicle'),
        ),
    ]
