# Generated by Django 5.0.2 on 2024-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0036_alter_vehicledetail_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ราคา (ไร่)'),
        ),
    ]
