# Generated by Django 4.2.9 on 2024-02-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Driver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=500, null=True)),
                ("address", models.TextField()),
                ("quantity", models.IntegerField()),
                ("phone", models.CharField(default="", max_length=15)),
                ("details", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("รออนุมัติ", "รออนุมัติ"),
                            ("อนุมัติแล้ว", "อนุมัติแล้ว"),
                            ("ไม่อนุมัติ", "ไม่อนุมัติ"),
                            ("กำลังดำเนินการ", "กำลังดำเนินการ"),
                            ("เสร็จสิ้น", "เสร็จสิ้น"),
                            ("ยกเลิก", "ยกเลิก"),
                        ],
                        default="รออนุมัติ",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.userfarmer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Driver.vehicle",
                    ),
                ),
            ],
        ),
    ]
