# Generated by Django 5.0.2 on 2024-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Farmer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="vehicle_type",
            field=models.CharField(default="", max_length=100, verbose_name="ประเภทรถ"),
        ),
    ]
