# Generated by Django 5.0.2 on 2024-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Farmer", "0004_rename_farmer_booking_name_booking_fullname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="time",
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle_type",
            field=models.CharField(default="", max_length=100, verbose_name="ประเภทรถ"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="booking",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
