# Generated by Django 5.0.2 on 2024-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdriver",
            name="driver_license",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver_licenses/"
            ),
        ),
        migrations.AddField(
            model_name="userdriver",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
