# Generated by Django 5.0.2 on 2024-05-30 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_userdriver_driver_license_userdriver_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdriver",
            name="driver_license",
        ),
        migrations.RemoveField(
            model_name="userdriver",
            name="is_approved",
        ),
    ]
