# Generated by Django 5.0.2 on 2024-05-14 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0001_initial"),
        ("Driver", "0008_delete_driverbooking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="booking",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="booking",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="fullname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("รออนุมัติ", "รออนุมัติ"),
                    ("อนุมัติแล้ว", "อนุมัติแล้ว"),
                    ("ไม่อนุมัติ", "ไม่อนุมัติ"),
                ],
                default="รออนุมัติ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Driver.vehicle"
            ),
        ),
    ]
