# Generated by Django 5.0.2 on 2024-05-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Booking", "0002_remove_booking_name_remove_booking_vehicle_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Accounts.userfarmer",
            ),
        ),
    ]
