# Generated by Django 5.0.2 on 2024-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0003_alter_booking_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="appointment_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
