# Generated by Django 5.0.2 on 2024-05-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Booking", "0004_booking_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Accounts.userfarmer",
            ),
        ),
    ]
