# Generated by Django 5.0.2 on 2024-05-16 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0010_alter_booking_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="farmer",
        ),
    ]
