# Generated by Django 5.0.2 on 2024-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0012_booking_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="appointment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
