# Generated by Django 5.0.2 on 2024-05-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Booking", "0013_alter_booking_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="driver",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Accounts.userdriver",
            ),
        ),
    ]
