# Generated by Django 5.0.2 on 2024-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0014_booking_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="driver",
        ),
    ]
