# Generated by Django 5.0.2 on 2024-05-16 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0018_alter_booking_farmer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="farmer",
        ),
    ]
