# Generated by Django 5.0.2 on 2024-05-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Booking", "0021_booking_driver_alter_booking_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="farmer",
        ),
        migrations.AlterField(
            model_name="booking",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Accounts.userdriver",
            ),
        ),
    ]
