# Generated by Django 5.0.2 on 2024-05-16 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
        ("Booking", "0022_remove_booking_farmer_alter_booking_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="driver",
        ),
        migrations.AddField(
            model_name="booking",
            name="farmer",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Accounts.userfarmer",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
