# Generated by Django 5.0.2 on 2024-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0024_remove_booking_created_at_remove_booking_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_appointment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
