# Generated by Django 5.0.2 on 2024-05-29 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0025_booking_end_appointment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="appointment_date",
            new_name="appointment_end_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="end_appointment_date",
            new_name="appointment_start_date",
        ),
    ]
