# Generated by Django 5.0.2 on 2024-05-29 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0027_driverschedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverSchedule",
        ),
    ]
