# Generated by Django 5.0.2 on 2024-05-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Accounts", "0002_userdriver_userfarmer_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("harvester_license", "ใบอนุญาตขับขี่รถเกี่ยวนวดข้าว")
                        ],
                        default="harvester_license",
                        max_length=50,
                    ),
                ),
                ("document", models.FileField(upload_to="verification_documents/")),
                ("verified", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
