# Generated by Django 5.0.2 on 2024-05-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_remove_userdriver_driver_license_and_more"),
        ("AuthAdmin", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrivingLicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="driving_license_documents/")),
                ("approved", models.BooleanField(default=False)),
                ("reason_for_rejection", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driving_license_documents",
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DriverDocument",
        ),
    ]
