# Generated by Django 5.0.2 on 2024-05-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_remove_userdriver_driver_license_and_more"),
        ("AuthAdmin", "0004_drivinglicensedocument_delete_driverdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card",
                    models.FileField(
                        upload_to="documents/id_cards/", verbose_name="บัตรประชาชน"
                    ),
                ),
                (
                    "license",
                    models.FileField(
                        upload_to="documents/licenses/",
                        verbose_name="ใบอนุญาตขับขี่รถเกี่ยวนวดข้าว",
                    ),
                ),
                (
                    "vehicle_registration",
                    models.FileField(
                        upload_to="documents/vehicle_registrations/",
                        verbose_name="ทะเบียนรถเกี่ยวนวดข้าว",
                    ),
                ),
                (
                    "purchase_receipt",
                    models.FileField(
                        upload_to="documents/purchase_receipts/",
                        verbose_name="ใบเสร็จการซื้อขายรถเกี่ยวนวดข้าว",
                    ),
                ),
                (
                    "insurance",
                    models.FileField(
                        upload_to="documents/insurances/",
                        verbose_name="หลักฐานการประกันภัย",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="เหตุผลที่ไม่ผ่าน"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DrivingLicenseDocument",
        ),
    ]
