# Generated by Django 5.0.2 on 2024-05-30 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AuthAdmin", "0005_document_delete_drivinglicensedocument"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
