# Generated by Django 5.0.2 on 2024-05-30 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AuthAdmin", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverDocument",
        ),
    ]
