# Generated by Django 5.0.2 on 2024-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfarmer",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
