# Generated by Django 5.0.2 on 2024-06-08 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_userdriver_groups_and_more"),
        ("auth_admin", "0003_delete_licensedocument"),
        ("bookings", "0002_alter_booking_farmer"),
        ("drivers", "0003_remove_detailvehicle_driver_detailvehicle_vehicle_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDriver",
        ),
        migrations.DeleteModel(
            name="UserFarmer",
        ),
    ]
