# Generated by Django 5.0.2 on 2024-06-08 19:55

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_userdriver_delete_userfarmer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
