# Generated by Django 5.0.2 on 2024-08-04 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_google_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="google_access_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_client_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_client_secret",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_refresh_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_token_expiry",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_token_uri",
        ),
    ]
