# Generated by Django 5.0.2 on 2024-09-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_group',
            new_name='group',
        ),
    ]
