# Generated by Django 5.0.2 on 2024-09-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_user_group_customuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_farmer_data', 'Can view farmer data'), ('can_view_driver_data', 'Can view driver data')]},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='group',
            new_name='user_group',
        ),
    ]
