# Generated by Django 5.0.2 on 2024-09-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_user_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_farmer_data', 'Can view farmer data'), ('can_view_driver_data', 'Can view driver data')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_users', to='auth.group'),
        ),
    ]
