# Generated by Django 5.0.2 on 2024-09-29 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_customuser_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
    ]
